export const FORMVALUES = {
  FIRSTNAME: 'firstname',
  NAME: 'name',
  LASTNAME: 'lastname',
  PHONE: 'mobile',
  PHONE2: 'phone',
  EMAIL: 'email',
  COMPANY: 'company',
  MESSAGE: 'message',
  CONDITIONS: 'conditionsAccepted',
  PARTOF: 'teamOrPartner',
  LINK: 'portfolio',
  SPECIALITY: 'areas',
  DATE: 'date',
  TIME: 'numberOfHours',
};
